eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 9091
spring:
  application:
    name: ProjectInfo
  datasource:
    url: jdbc:postgresql://localhost:5432/microserviceproject
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        dialect: org.hibernate.dialect.PostgreSQLDialect