eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ProjectInfo
          uri: http://localhost:9091
          predicates:
            - Path=/ust/**
        - id: EmployeeInfo
          uri: http://localhost:9092
          predicates:
            - Path=/ustemps/**