server:
  port: 8090
spring:
  application:
    name: security
  datasource:
    url: jdbc:postgresql://localhost:5432/userCredentials
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        dialect: org.hibernate.dialect.PostgreSQLDialect